name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  REPO_NAME: rsmonte/actions-backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login into Docker
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build -t ${{env.REPO_NAME}}:latest .
    - name: Push to DockerHUB
      run: docker push ${{env.REPO_NAME}}:latest

  deploy:
    runs-on: self-hosted
    needs: build  
    steps:
      - name: Login into Docker
        env: 
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Pulling Docker Image
        run: sudo docker pull ${{env.REPO_NAME}}:latest
      - name: Removing Old Docker Image
        run: sudo docker rm -f actions-backend-server || true 
      - name: Starting Docker Image
        run: sudo docker run -d -p 3000:3000 --name actions-backend-server ${{env.REPO_NAME}}:latest
      - name: test
        run: sudo dcoker ps
