name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  REPO_NAME: actions-backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login into Docker
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build -t ${{env.REPO_NAME}} .
    - name: Push to DockerHUB
      run: docker push rsmonte/${{env.REPO_NAME}}:latest
